config/routes.rb
Rails.application.routes.draw do
  root 'tear_of_lapislazuli#index'
  get '/about', to: 'tear_of_lapislazuli#about'
  get '/character', to: 'tear_of_lapislazuli#character'
  get '/download', to: 'tear_of_lapislazuli#download'
  get '/link', to: 'tear_of_lapislazuli#link'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tear_of_lapislazuli_controller.rb
class TearOfLapislazuliController < ApplicationController
  def index
  end

  def about
  end

  def character
  end

  def download
  end

  def link
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tear_of_lapislazuli_helper.rb
module TearOfLapislazuliHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="bs-docs-section clearfix">
    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                  <li><%= link_to "Top", root_path %></li>
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Character", character_path %></li>
                  <li><%= link_to "Download", download_path %></li>
                  <li><%= link_to "Creatodon", "https://gamelinks007.net" %></li>
                  <li><%= link_to "Source", "https://github.com/S-H-GAMELINKS/CreatodonFolio" %></li>
                  <li><%= link_to "Link", link_path %></li>
                </ul>
              </div>
            </div>
          </nav>
        </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "瑠璃の泪 / Tear of Lapislazuli", root_path, :class => "navbar-brand" %>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li><%= link_to "Top", root_path%></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Character", character_path %></li>
          <li><%= link_to "Download", download_path %></li>
          <li><%= link_to "Creatodon", "https://gamelinks007.net" %></li>
          <li><%= link_to "Source", "https://github.com/S-H-GAMELINKS/Tear.Of.Lapislazuli.Web" %></li>
          <li><%= link_to "Link", link_path %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_template.html.erb
  <head>
    <title>Tear Of Lapislazuli Web</title>
    <%= csrf_meta_tags %>

      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <link rel="stylesheet" type="text/css" href="css/bootstrap.css">

      <style type="text/css">
      body { padding-top: 80px; }
      @media ( min-width: 768px ) {
      #banner {
        min-height: 300px;
        border-bottom: none;
      }
      .bs-docs-section {
        margin-top: 8em;
      }
      .bs-component {
        position: relative;
      }
      .bs-component .modal {
        position: relative;
        top: auto;
        right: auto;
        left: auto;
        bottom: auto;
        z-index: 1;
        display: block;
      }
      .bs-component .modal-dialog {
        width: 90%;
      }
      .bs-component .popover {
        position: relative;
        display: inline-block;
        width: 220px;
        margin: 20px;
      }
      .nav-tabs {
        margin-bottom: 15px;
      }
      .progress {
        margin-bottom: 10px;
      }
    }
    </style>

    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/template'%>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/tear_of_lapislazuli/about.html.erb
<br>
<div div style="text-align:center">
<h2>
数年前、火事により家族を失った男：篠田幸太郎。<br>
彼は亡くなった妻から「お人好し」と呼ばれていた。<br>
その「お人好し」加減たるや<br>
「道に迷っている人を見かければ、一緒になって地図を見て迷子になった」<br>
「電車で忘れ物をした人を追いかけてしまって打ち合わせに遅刻した」りするほど。<br>
<br>
そんな彼だからこそ、目の前で泣いている一人の少女を放っておくことが出来なかった。<br>
<br>
少女の名は瑠璃といい、彼女は追ってから逃げている最中とのことだ。<br>
幸太郎は事情を聞き、暫くの間自宅に匿うことを約束する。<br>
<br>
これは、そんなお人好しな中年と少女の物語。
</h2>
</div>

app/views/tear_of_lapislazuli/character.html.erb
<br>
<div div style="text-align:center">
<h1>Character</h1>

<h2>篠田幸太郎</h2><br>
数年前に死別したかつての家族の思い出が残る家で孤独に過ごしている男性。<br>
自宅への帰り道で、泣きじゃくる瑠璃と出会う。<br>
<br>
何者かから追われている瑠璃の事情を聴き、匿う。<br>
<br>

<h2>瑠璃</h2>
幸太郎が自宅への帰り道で出会った少女<br>
何者かから逃げており、酷く怯えている。<br>
<br>
幸太郎に匿われ、生活していく中で少しづつ心を開いていくが―――？<br>

<h2></h2>
</div>

app/views/tear_of_lapislazuli/download.html.erb
<div div style="text-align:center">

<h1>「瑠璃の泪」は以下のWebサイトよりダウンロードできます</h1>

<h1><%= link_to "フリーゲーム夢現", "https://freegame-mugen.jp/adventure/game_6784.html"%></h1>

<h1><%= link_to "ふりーむ", "" %></h1>

<h1><%= link_to "ゲームリンクス制作物置き場", "https://ux.getuploader.com/GAMELINKS001/download/70" %></h1>

app/views/tear_of_lapislazuli/index.html.erb
<br><br>

<div div style="text-align:center">

    <h1>瑠璃の泪 / Tear of Lapislazuli</h1>

<br><br>

    <h1>家族を失った孤独な男性と、少女の交流―――</h1>

<br><br>

    <%= video_tag('pv.mp4', :controls => true) %>
</div>

app/views/tear_of_lapislazuli/link.html.erb
<br>
<div div style="text-align:center">

<h1><%= link_to "「瑠璃の泪」のソースコード公開先", "https://github.com/S-H-GAMELINKS/Tear.of.Lapislazuli" %></h1>

<h1><%= link_to "Creatodon", "https://gamelinks007.net/about/more" %></h1>

<h1><%= link_to "ゲームリンクス", "https://gamelinksweb.herokuapp.com" %></h1>

</div>